<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
    <SupportedOSPlatformVersion>24</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <ApplicationId>com.luofaiz.igolibrary</ApplicationId>
    <ApplicationVersion>7</ApplicationVersion>
    <ApplicationDisplayVersion>1.6</ApplicationDisplayVersion>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <TrimMode>partial</TrimMode>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\IGoLibrary.Ex.Application\IGoLibrary.Ex.Application.csproj" />
    <ProjectReference Include="..\IGoLibrary.Ex.Domain\IGoLibrary.Ex.Domain.csproj" />
    <ProjectReference Include="..\IGoLibrary.Ex.Infrastructure\IGoLibrary.Ex.Infrastructure.csproj" />
  </ItemGroup>
</Project>
